language: node_js
node_js:
  - 14.5.0
before_install:
  # Only deploy if the version number has changed
  - |
    if git diff --unified=0 $TRAVIS_COMMIT_RANGE package.json | grep version ; then
      export VERSION_CHANGED="yes"
    fi
  - npm i -g npm
install:
  - npm install
before_deploy:
  - npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_KEY
  on:
    branch: master
    condition: "$VERSION_CHANGED == 'yes'"
